ogcio/building-blocks-sdk

package.json
src/cli/index.ts
src/clients/messaging-api/open-api-definition.json
src/clients/messaging-api/schema.d.ts

Fix in code
added command in package json

feat: add command in package.json

---

src/cli/clients-configurations/clients-configuration.json
src/cli/clients-configurations/read-configuration-file.ts
src/cli/update-clients-command.ts

Added permissions on configuration file

Feat: update configurations file with permissions

---

src/cli/clients-configurations/clients-configuration.json
src/clients/payments-api/open-api-definition.json
src/clients/payments-api/schema.d.ts
src/clients/profile-api/open-api-definition.json
src/clients/profile-api/schema.d.ts
src/clients/scheduler-api/open-api-definition.json
src/clients/scheduler-api/schema.d.ts
src/clients/upload-api/open-api-definition.json
src/clients/upload-api/schema.d.ts

Added the configuration and the schema for the other services

Feat: added definitions for all services

---

src/cli/update-clients-command.ts
src/client/clients/messaging-api/open-api-definition.json

Added dry run on updating clients

Feat: add dry run

---

package-lock.json
src/index.ts
src/types/index.ts

- fix `package-lock.json` version to `0.0.3`
- formatting, linting

chore: new version, fix format,lint

---

package-lock.json
package.json
src/client/base-client.ts
src/client/clients/messaging/index.ts
src/client/clients/payments/index.ts
src/client/clients/profile/index.ts
src/client/clients/scheduler/index.ts
src/client/clients/upload/index.ts

- Added token deletion
- Changed visibility to client in subclasses to prevent exposure to outer world

feat: added token deletion

---

package-lock.json
package.json
src/client/base-client.ts
src/client/clients/payments/index.ts

Added new method in payments to get the refreshed token

Fix: missing payments method

---

package-lock.json
package.json

- fix `window` is not defined 
- improve `customDimensions` type
- fix immutability `setTrackingContext`

chore: update analytics sdk + bump

---

README.md
package-lock.json
package.json
src/__tests__/index.test.ts
src/types/index.ts

Fix the building blocks configuration type for Analytics

Fix(): Analytics blocks type

---

.azure/pipeline.yaml
.azure/templates/pnpm-install.yaml
.gitignore
kics-config.json
vitest.config.mts

Some CI improvements
- build check
- lint & formatting check
- test check
In the future we can also manage changelogs and releases via CI, I've prepared something on Analytics, but I'd like to write a proposal document and discuss it with the teams, before integrating it here 
after merge this PR I link the pipeline file to azure

chore(ci): add azure pipeline ci checks

---

package.json
src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

Update payments schema with optional `redirectUrl` in `metadata`

feat: update payments schema

---

package.json

0.1.2 was alredy published but version on package json not updated

chore: 0.1.3

---

package.json
src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

23328 update Realex schema

---

README.md
package.json
src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

Updated Journey schema:
- add runStepId parameter to the /executor/transition API call

feat: update journey schema

---

package.json
src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts
src/client/clients/payments/index.ts
src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

New payment request API call added to the SDK.

feat(23769): new payment request call added

---

package.json
src/__tests__/client/utils/client-utils.test.ts
src/client/base-client.ts
src/client/clients/featureFlags/index.ts
src/client/clients/journey/index.ts
src/client/clients/messaging/index.ts
src/client/clients/payments/index.ts
src/client/clients/profile/index.ts
src/client/clients/scheduler/index.ts
src/client/clients/upload/index.ts
src/client/utils/client-utils.ts
src/index.ts
src/types/index.ts

Log requests and responses if a logger is passed
Exported types to improve DX for users
(Lot of changes but I just added parameters to the formatResponse)

Feat: log requests

---

package.json
src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts
src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

Modify messaging journey step data schema:
- removed organizationId
- added generatePDF
- added recipient

feat(23806): modify messaging journey step data schema

---

package.json
pnpm-lock.yaml

**Bug Fixes**
analytics-sdk: Custom dimentions management during trackPush and initTracker (https://github.com/ogcio/analytics/issues/360) ([7d3ed42](https://github.com/ogcio/analytics/commit/7d3ed42ba9fab520c686c0334ca718f87f68096f))
https://github.com/ogcio/analytics/blob/main/packages/analytics-sdk/CHANGELOG.md

feat: update analytics beta 6

---

.azure/pipeline.yaml

fixing CI errors: https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_build/results?buildId=28544&view=logs&j=100f94f0-8786-5f26-05fe-113c08da6c8a&t=f8936632-7fef-5187-93f5-5a282bcb6e2f

ci: add missing pipeline variables

---

src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

chore: update journey schema

---

src/client/clients/payments/index.ts
src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

Add new method to Payments API for Stripe payment intent creation

feat: add method for Stripe payment intent creation

---

src/client/clients/payments/index.ts
src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

Added new Refund payments API calls to Payments API

feat: add refund payments calls to payments api.

---

src/client/clients/payments/index.ts
src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts
src/clients-configurations/clients-configuration.json

Add Cancel payment endpoint to the Payments SDK.

feat(24831): add cancel payment endpoint

---

src/client/clients/journey/index.ts
src/client/clients/messaging/index.ts
src/client/clients/payments/index.ts
src/client/clients/profile/index.ts
src/client/clients/upload/index.ts
src/client/utils/client-utils.ts

check on method params, if they are mandatory strings, that have length > 0

Fix:fixed empty string

---

src/client/clients/messaging/index.ts
src/client/clients/messaging/open-api-definition.json
src/client/clients/messaging/schema.ts

Add date parameters to message events search
[Azure](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/24132)

chore(): add date parameters to message events search

---

src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

feat(24761): update journey sdk

---

src/client/clients/journey/index.ts
src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts
src/clients-configurations/clients-configuration.json

[24901](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/24901)
Update `journey` schema and add method to update run status.
Set `journey` and `payments` definitions update to `true`.

feat: journey submission status

---

src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

fix: fix journey sdk

---

src/client/clients/profile/index.ts
src/client/clients/profile/open-api-definition.json
src/client/clients/profile/schema.ts
src/clients-configurations/clients-configuration.json

- updated profile schemas
- updated default profile permissions
- added possibility to ask for private details
- added download csv

Feat(profile): 24274 - added possibility to ask for private details

---

package.json
pnpm-lock.yaml

Update packages and analytics SDK:
[Analytics SDK Changelog](https://github.com/ogcio/analytics/blob/main/packages/analytics-sdk/CHANGELOG.md#010-beta14-2025-02-12)
* analytics sdk offline mode ([#425](https://github.com/ogcio/analytics/issues/425)) ([a44aea5](https://github.com/ogcio/analytics/commit/a44aea57d54fac5656f1c943cfb61898feb76a8b))
offline mode doc is in the analytics repo: https://github.com/ogcio/analytics/blob/main/apps/docs/docs/services/sdk.mdx#offline-mode

feat: update analytics sdk and packages

---

package.json
src/__tests__/client/clients/base-client.test.ts
src/__tests__/client/clients/featureFlags/index.test.ts
src/__tests__/utils.ts
src/client/base-client.ts
vitest.config.mts

- ensure that the check on timestamps are made on both milliseconds
- refactoring

Fix: check token expiration

---

src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts
src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

Dynamic content translation update

feat: dynamic content translation update

---

src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

Small fix in Payments API FullTransactions schema.

fix: payments api

---

src/client/clients/profile/index.ts
src/client/clients/profile/open-api-definition.json
src/client/clients/profile/schema.ts

chore(): add profile missing endpoints

chore(): add profile missing endpoints

---

src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

feat: set language in journey api

---

src/client/clients/profile/open-api-definition.json
src/client/clients/profile/schema.ts

feat(): update profile-api schema

---

src/client/clients/profile/index.ts
src/client/clients/profile/open-api-definition.json
src/client/clients/profile/schema.ts

- updated put and patch
- remove *user(s) methods

feat(profile-api): updated put and patch profiles

---

src/client/clients/journey/index.ts
src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

Journey submission tags related API changes.

feat(26220): journey submission tags

---

src/client/clients/journey/index.ts
src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

feat: rename tags route

---

src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

Change redirectURLs to support language-based URLs.

feat(26447): maintain selected language

---

package.json
pnpm-lock.yaml

Bump `"@ogcio/analytics-sdk": "0.1.0-beta.16"`

feat(): update analytics package

---

package.json
pnpm-lock.yaml

feat: bump openapi-fetch version

---

src/client/clients/payments/index.ts
src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

Delete payment transaction API call.

feat(25295): delete payment transaction api call

---

src/client/clients/journey/index.ts
src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

Add Journey Submission delete API call

feat: add delete journey submission api call

---

package.json
pnpm-lock.yaml

[28280](https://dev.azure.com/OGCIO-Digital-Services/Digital%20Services%20Programme/_workitems/edit/28280)
Update analytics-sdk reducing log verbosity

chore: update analytics-sdk AB#28280

---

src/client/base-client.ts
src/types/index.ts

fix: handle invalid grant error

---

src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

Remove user info from Payments

feat: payments - remove user info

---

src/client/clients/payments/open-api-definition.json
src/client/clients/payments/schema.ts

feat: payments refund user fix

---

src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

remove choosen signin method from create run call

feat: remove choosen signin method from create run call

---

src/client/clients/journey/open-api-definition.json
src/client/clients/journey/schema.ts

feat: jb audit logs
